version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: aiohttp
    versions:
    - 3.7.4
  - dependency-name: nodeenv
    versions:
    - 1.5.0
