image: tailhook/vagga:v0.7.2-93-g0884e15

stages:
- build
- test
- deploy

before_script:
- export FEATURES_SHASH=`vagga _version_hash --short features`
- export TEST_SHASH=`vagga _version_hash --short test`
- export MYSQL_SHASH=`vagga _version_hash --short mysql`

vagga:build:
  stage: build
  # basically just run pre-commit linters
  script:
  - vagga _build test &
  - vagga _build mysql &
  - wait

vagga:lint:
  stage: test
  # basically just run pre-commit linters
  script: vagga lint

vagga:test:
  stage: test
  script: vagga test
