before_script:
  # installing pre-commit
  - apt-get install -y python-dev python-pip
  - pip install -c requirements/constraints.txt -r requirements/linters.txt -r requirements/common.txt
  - pre-commit install

test:
  script:
    # basically just run pre-commit linters
    - pre-commit run --all-files
