before_script:
  # installing pre-commit
  - pip install -c requirements/constraints.txt -r requirements/linters.txt -r requirements/common.txt
  - pre-commit install

test:
  script:
    #basicly just run pre-commit linters
    - pre-commit run --all-files
