image: 'python:3.6.1'
before_script:
  # installing pre-commit
  - pip install -c requirements/constraints.txt -r requirements/linters.txt -r requirements/test.txt -r requirements/common.txt
  - pre-commit install-hooks

lint:
  # basically just run pre-commit linters
  script: pre-commit run --all-files

test:
  script: py.test
