image: 'python:3.6.1'
before_script:
  # installing pre-commit
  - pip install -c requirements/constraints.txt -r requirements/linters.txt -r requirements/test.txt -r requirements/common.txt
  - pre-commit install-hooks

test:
  script:
    # basically just run pre-commit linters
    - pre-commit run --all-files
    - py.test
