-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: 5bf6c09
    hooks:
    -   id: trailing-whitespace
    -   id: flake8
        args: [--max-line-length=120]
    -   id: check-merge-conflict
    -   id: double-quote-string-fixer
    -   id: end-of-file-fixer
    -   id: name-tests-test
    -   id: debug-statements
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-byte-order-marker
    -   id: check-case-conflict
    -   id: check-docstring-first
    -   id: check-json
    -   id: pretty-format-json
    -   id: check-symlinks
    -   id: check-yaml
        exclude: (vagga|feature_api/config)\.yaml
    -   id: detect-private-key
    -   id: requirements-txt-fixer

-   repo: git://github.com/FalconSocial/pre-commit-mirrors-pep257
    sha: f464d46
    hooks:
    -   id: pep257

-   repo: git://github.com/Lucas-C/pre-commit-hooks
    sha: 1e30aa4
    hooks:
    -   id: remove-tabs

-   repo: git://github.com/Lucas-C/pre-commit-hooks-lxml
    sha: 44f1a42
    hooks:
    -   id: forbid-html-img-without-alt-text

-   repo: git://github.com/detailyang/pre-commit-shell
    sha: 75af325
    hooks:
    -   id: shell-lint
